---
- name: Ensure Allow Tcp Forwarding yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#AllowTcpForwarding '
    line: AllowTcpForwarding yes

- name: Ensure Allow Tcp Forwarding yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PermitTunnel '
    line: PermitTunnel yes

- name: Create rke user
  ansible.builtin.user:
    name: '{{ rke_user }}'
    password: "{{ rke_user_password | password_hash('sha512') }}"
    update_password: on_create
    shell: /bin/bash
    groups:
      - sudo
      - docker
    state: present
    create_home: yes

- name: Create ssh directory
  become_user: '{{ rke_user }}'
  file:
    path: $HOME/.ssh
    mode: '0700'
    state: directory

- name: Create ssh directory authorize
  become_user: '{{ rke_user }}'
  file:
    path: $HOME/.ssh/authorized_keys
    mode: '0600'
    state: touch
