--- # Root User
- name: Install SELInux Util
  become: true
  apt:
    name: selinux-utils
    state: present

- name: disable SELinux
  become: true
  ignore_errors: true
  shell: 'setenforce 0'

- name: Add a line kubernetes systemctl configuration
  become: true
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: '{{ item }}'
    create: yes
  with_items:
    - net.bridge.bridge-nf-call-ip6tables = 1
    - net.bridge.bridge-nf-call-iptables = 1
    - net.ipv4.ip_forward = 1

- name: Apply systemctl configuration
  become: true
  shell: sysctl --system

- name: Get kubectl stable version
  become: true
  uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: yes
  register: latest_kubectl
  until: latest_kubectl.status == 200
  delay: 10
  retries: 3

- name: Download kubectl
  get_url:
    url: 'https://dl.k8s.io/release/{{ latest_kubectl.content }}/bin/linux/amd64/kubectl'
    dest: /tmp
  register: download
  until: download.status_code == 200
  delay: 10
  retries: 3

- name: Install kubectl
  become: true
  shell: install -o root -g root -m 0755 /tmp/kubectl /usr/local/bin/kubectl

- name: Install BashCompletion
  become: true
  apt:
    name: bash-completion
    state: present

- name: Source BashCompletion
  become: true
  shell: 'kubectl completion bash | sudo tee /etc/bash_completion.d/kubectl > /dev/null'

- name: Add a line Kubectl Alias
  become: true
  lineinfile:
    path: ~/.bashrc
    line: '{{ item }}'
  with_items:
    - alias k=kubectl
    - complete -F __start_kubectl k
